# Minify HTML, CSS, JS f端r schnellere Ladezeiten
plugins:
  - jekyll-minifier
title: TaxiGo Neum端nster
email: taxigoneumuenster@gmail.com
description: >-
  Sicheres und bequemes Taxi in Neum端nster. Business-Fahrten, Sch端lerfahrten, Kurierfahrten, Flughafentransfer und mehr.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xn--taxigoneumnster-8vb.de" # the base hostname & protocol for your site
lang: de
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-minifier
exclude:
  - node_modules
  - README.md
  - postcss.config.js
  - tailwind.config.js
  - LICENSE
  - CNAME
  - index.md
  - .devcontainer
  - .vscode
# assets/fonts und assets/css werden nicht ausgeschlossen, damit sie nach _site kopiert werden
jekyll-minifier:
  preserve_php: true                # Default: false
  remove_spaces_inside_tags: true   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: true      # Default: false
  remove_quotes: false              # Default: false
  compress_css: true                # Default: true
  compress_javascript: true         # Default: true
  compress_json: true               # Default: true
  simple_doctype: false             # Default: false
  remove_script_attributes: false   # Default: false
  remove_style_attributes: false    # Default: false
  remove_link_attributes: false     # Default: false
  remove_form_attributes: false     # Default: false
  remove_input_attributes: false    # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false       # Default: false
  remove_https_protocol: false      # Default: false
  preserve_line_breaks: false       # Default: false
  simple_boolean_attributes: false  # Default: false
  compress_js_templates: false      # Default: false
  preserve_patterns:                # Default: (empty)
  terser_args:                      # Default: (empty)